[build]
  base = " "
  command = "CI=false npm run build"
  publish = "build"

[[redirects]]
  from = "/pdf.worker.min.js"
  to = "/pdf.worker.min.js"
  status = 200

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

