[build]
  base = " "
  command = "CI=false npm run build"
  publish = "build"

# ✅ Redirect all API calls to your EC2 backend
[[redirects]]
  from = "/api/*"
  to = "https://api.eethmhmultimedia.com/api/:splat"
  status = 200
  force = true

# ✅ Keep PDF worker local
[[redirects]]
  from = "/pdf.worker.min.js"
  to = "/pdf.worker.min.js"
  status = 200

# ✅ Catch-all route for React SPA
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
