import promotions from './promotionsAPI';
import messaging from './messagingAPI';
import videos from './videosAPI';
import media from './mediaAPI';
import services from './servicesAPI';
import invoices from './invoicesAPI';
import newsletter from './newsletterAPI';
import reviews from './reviewsAPI';
import bookings from './bookingAPI';
import contact from './contactAPI';
import analytics from './analyticsAPI';
import misc from './miscAPI';
import auth from './authAPI';

const API = {
  auth,        // /api/accounts/...
  promotions,  // /api/promotions/...
  messaging,   // /api/messaging/messages/... + /api/accounts/profiles/send-message/
  videos,      // /api/videos/videos/...
  media,       // /api/media/...
  services,    // /api/services/...
  invoices,    // /api/invoices/invoices/...
  newsletter,  // /api/newsletter/...
  reviews,     // /api/reviews/...
  bookings,    // /api/bookings/...
  contact,     // /api/contact/send/
  analytics,   // /api/analytics/...
  misc,        // /api/health/, /api/csrf/
};

export default API;
